version: '3.8'

services:
  load_balancer:
    build:
      context: .
      dockerfile: Dockerfile.loadbalancer
    container_name: load_balancer
    ports:
      - "5000:5000" # Port mapping for the load balancer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Mount the Docker socket to manage containers
    privileged: true # Grant privileges to manage Docker
    environment:
      - SERVER_ID=load_balancer # Environment variable for the load balancer
    depends_on:
      - server_1
      - server_2
      - server_3

  server_1:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - SERVER_ID=server_1
    networks:
      - my_network

  server_2:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - SERVER_ID=server_2
    networks:
      - my_network

  server_3:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - SERVER_ID=server_3
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
