version: '3.8'

services:
  load_balancer:
    build:
      context: .
      dockerfile: Dockerfile.loadbalancer
    container_name: load_balancer
    ports:
      - "5000:5000" # Expose port 5000 for the load balancer service to receive requests
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Mount the Docker socket to manage containers
      
    privileged: true
    environment:
      - SERVER_IMAGE_NAME=dist-sys-a1-test-server # Specify the Docker image for the server containers
      - SERVER_ID=load_balancer
    networks:
      - my_network

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: Server1
    environment:
      - SERVER_ID=server_1
    networks:
      - my_network






networks:
  my_network:
    driver: bridge
